source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

# Core Libraries
def core()
  pod 'Moya-Gloss', :path => '../'
  pod 'Moya-Gloss/RxSwift', :path => '../'
  pod 'Moya-Gloss/ReactiveSwift', :path => '../'
  pod 'Gloss', '~> 1.0'
  pod 'Alamofire', '~> 4.0'
  pod 'Moya', '8.0.0-beta.6'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ReactiveSwift', '1.0.0-alpha.4'
end

# Testing Libraries
def testing()
  pod 'Quick'
  pod 'Nimble'
end

target 'Demo' do
  platform :ios, '9.0'
  core
end

target 'Tests' do
  platform :ios, '9.0'
  core
  testing
end
