source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

# Core Libraries
def core()
  pod 'Moya-Gloss', :path => '../'
  pod 'Moya-Gloss/RxSwift', :path => '../'
end

target 'Demo' do
  platform :ios, '8.0'
  core
end